/* global CLASSES */
'use strict';

const CLASSES = [
  {
    id: 'biology-honors',
    name: 'Biology Honors',
    description: 'Advanced study of life science covering molecular biology, cell structure, genetics, evolution, and ecology.',
    unit: 'Science',
    icon: '🧬',
    studyGuides: [
      {
        title: 'Unit 1 — Introduction to Biology',
        content: [
          'Biology is the scientific study of life and living organisms.',
          'The eight properties of life: order, metabolism, growth/development, response to stimuli, reproduction, homeostasis, evolutionary adaptation, and cells.',
          'The three domains of life are Bacteria, Archaea, and Eukarya; kingdoms include Animalia, Plantae, Fungi, Protista.',
          'The biological hierarchy from smallest to largest: atom → molecule → organelle → cell → tissue → organ → organ system → organism → population → community → ecosystem → biosphere.',
          'The scientific method: observation → question → hypothesis → experiment → data analysis → conclusion.',
          'A controlled experiment has an independent variable, a dependent variable, and a control group.',
          'Evolution is the change in heritable traits of a population over successive generations.',
          'Natural selection: organisms with favorable traits are more likely to survive and reproduce.',
          'Taxonomy classifies organisms using: Domain, Kingdom, Phylum, Class, Order, Family, Genus, Species.',
          'Binomial nomenclature uses genus and species names (e.g., Homo sapiens) in italics.',
        ]
      },
      {
        title: 'Unit 2 — Chemistry of Life',
        content: [
          'All matter is made of atoms; atoms bond to form molecules.',
          'Covalent bonds share electrons; ionic bonds transfer electrons between atoms.',
          'Hydrogen bonds are weak attractions between slightly positive H and slightly negative atoms (O or N).',
          'Water is polar, enabling hydrogen bonds and cohesion, adhesion, and high specific heat.',
          'The pH scale ranges from 0 (most acidic) to 14 (most basic/alkaline); pH 7 is neutral.',
          'Acids donate H⁺ ions; bases accept H⁺ ions (or donate OH⁻).',
          'Biological macromolecules: carbohydrates, lipids, proteins, and nucleic acids.',
          'Carbohydrates (sugars): monomer = monosaccharide; polymer = polysaccharide; functions include energy storage (glycogen, starch) and structure (cellulose).',
          'Lipids: fats, oils, phospholipids, waxes; not polymers; functions include energy storage, membrane structure, and insulation.',
          'Proteins: monomer = amino acid; polymer = polypeptide; functions include enzymes, transport, structure, signaling, and defense.',
          'Nucleic acids: monomer = nucleotide; polymers = DNA and RNA; store and transfer genetic information.',
          'Enzymes are biological catalysts that lower activation energy; they are specific to their substrate.',
        ]
      },
      {
        title: 'Unit 3 — Cell Biology',
        content: [
          'Cell theory: all living things are made of cells; the cell is the basic unit of life; all cells come from pre-existing cells.',
          'Prokaryotic cells (Bacteria, Archaea): no membrane-bound nucleus, no membrane-bound organelles, smaller (~1–10 µm).',
          'Eukaryotic cells (animals, plants, fungi, protists): membrane-bound nucleus, membrane-bound organelles, larger (~10–100 µm).',
          'Key organelles: nucleus (DNA storage), mitochondria (ATP production), ribosomes (protein synthesis), ER (processing), Golgi apparatus (packaging/shipping).',
          'Plant cells also have: cell wall, chloroplasts, central vacuole, plasmodesmata.',
          'Photosynthesis occurs in chloroplasts: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂.',
          'Light reactions (thylakoid membrane) convert light to ATP and NADPH; Calvin cycle (stroma) fixes CO₂ into G3P.',
          'Cellular respiration occurs mainly in mitochondria: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ~36–38 ATP.',
          'Glycolysis (cytoplasm) → Pyruvate oxidation → Krebs cycle (matrix) → Electron transport chain (inner membrane).',
          'Fermentation (anaerobic): lactic acid fermentation or alcoholic fermentation; produces only 2 ATP net.',
          'The plasma membrane is a phospholipid bilayer with embedded proteins; it is selectively permeable.',
          'Passive transport: diffusion, osmosis, facilitated diffusion (no energy); active transport uses ATP.',
          'Chlorophyll a and b absorb red and blue light most efficiently; green light is reflected (why plants look green).',
          'The light-dependent reactions split water (photolysis) to produce O₂, ATP, and NADPH.',
          'Photosystem II absorbs light at ~680 nm; Photosystem I absorbs at ~700 nm.',
          'The Calvin cycle requires 3 CO₂, 9 ATP, and 6 NADPH to produce one G3P molecule.',
          'Rubisco is the enzyme that catalyzes carbon fixation in the Calvin cycle.',
          'Aerobic respiration produces ~36–38 ATP per glucose; most ATP is made at the ETC.',
          'The electron transport chain uses NADH and FADH₂ to pump H⁺ across the inner mitochondrial membrane, driving ATP synthase.',
          'Chemiosmosis: flow of H⁺ through ATP synthase drives phosphorylation of ADP → ATP.',
          'Substrate-level phosphorylation produces ATP directly during glycolysis and the Krebs cycle.',
          'Acetyl-CoA enters the Krebs cycle and is fully oxidized, releasing CO₂ and producing NADH, FADH₂, and ATP.',
        ]
      }
    ],
    qbank: [
      // ── UNIT 1 — Introduction to Biology ──────────────────────────────────
      { unit: 1, q: 'Which of the following is NOT considered a property of life?', choices: ['Reproduction', 'Metabolism', 'Crystalline structure', 'Homeostasis'], answer: 2 },
      { unit: 1, q: 'Which domain includes organisms with membrane-bound nuclei?', choices: ['Bacteria', 'Archaea', 'Eukarya', 'Protista'], answer: 2 },
      { unit: 1, q: 'The correct order of the biological hierarchy from smallest to largest is:', choices: ['Cell → Organ → Tissue → Organism', 'Atom → Molecule → Organelle → Cell', 'Ecosystem → Community → Population → Organism', 'Organ → Tissue → Cell → Organelle'], answer: 1 },
      { unit: 1, q: 'In a controlled experiment, the variable that the scientist deliberately changes is called the:', choices: ['Dependent variable', 'Controlled variable', 'Independent variable', 'Constant'], answer: 2 },
      { unit: 1, q: 'Which scientist proposed the theory of natural selection?', choices: ['Gregor Mendel', 'Louis Pasteur', 'Charles Darwin', 'Robert Hooke'], answer: 2 },
      { unit: 1, q: 'The scientific name Homo sapiens follows the system of:', choices: ['Binomial nomenclature', 'Systemic classification', 'Hierarchical taxonomy', 'Phenotypic grouping'], answer: 0 },
      { unit: 1, q: 'Natural selection acts on which of the following?', choices: ['Genotype only', 'Phenotype', 'DNA directly', 'Non-heritable traits'], answer: 1 },
      { unit: 1, q: 'Which level of biological organization is directly above the community?', choices: ['Population', 'Organism', 'Ecosystem', 'Biosphere'], answer: 2 },
      { unit: 1, q: 'A hypothesis must be:', choices: ['Proven true', 'Testable and falsifiable', 'Based on prior experiments only', 'Supported by multiple theories'], answer: 1 },
      { unit: 1, q: 'Taxonomy classifies organisms using which sequence?', choices: ['Kingdom, Phylum, Class, Order, Family, Genus, Species', 'Domain, Class, Kingdom, Order, Phylum, Genus, Species', 'Species, Genus, Family, Order, Class, Phylum, Kingdom', 'Domain, Phylum, Kingdom, Class, Family, Order, Species'], answer: 0 },
      { unit: 1, q: 'Archaea are most closely related to:', choices: ['Bacteria', 'Fungi', 'Plants', 'Eukarya'], answer: 3 },
      { unit: 1, q: 'The maintenance of a stable internal environment is called:', choices: ['Metabolism', 'Homeostasis', 'Adaptation', 'Reproduction'], answer: 1 },
      { unit: 1, q: 'Which of the following best defines evolution?', choices: ['Change in an individual organism over time', 'Change in heritable traits of a population over generations', 'Survival of the strongest individual', 'Genetic mutation in a single organism'], answer: 1 },
      { unit: 1, q: 'The control group in an experiment:', choices: ['Receives the experimental treatment', 'Is exposed to the independent variable', 'Is used as a baseline for comparison', 'Contains no constants'], answer: 2 },
      { unit: 1, q: 'Which kingdom contains multicellular organisms that perform photosynthesis?', choices: ['Fungi', 'Animalia', 'Plantae', 'Bacteria'], answer: 2 },
      { unit: 1, q: 'Which of the following is the broadest taxonomic category?', choices: ['Species', 'Genus', 'Kingdom', 'Domain'], answer: 3 },
      { unit: 1, q: 'Organisms that break down dead organic matter are called:', choices: ['Producers', 'Consumers', 'Decomposers', 'Herbivores'], answer: 2 },
      { unit: 1, q: 'The idea that all cells come from pre-existing cells is part of:', choices: ['Evolution theory', 'Cell theory', 'Germ theory', 'Gene theory'], answer: 1 },
      { unit: 1, q: 'Which process converts light energy into chemical energy?', choices: ['Cellular respiration', 'Fermentation', 'Photosynthesis', 'Chemosynthesis'], answer: 2 },
      { unit: 1, q: 'The process by which populations change over time in response to environmental pressures is called:', choices: ['Genetics', 'Evolution', 'Ecology', 'Taxonomy'], answer: 1 },
      { unit: 1, q: 'Which of the following is an example of an abiotic factor in an ecosystem?', choices: ['Trees', 'Bacteria', 'Temperature', 'Birds'], answer: 2 },
      { unit: 1, q: 'The scientific method begins with which step?', choices: ['Forming a hypothesis', 'Making an observation', 'Designing an experiment', 'Analyzing data'], answer: 1 },
      { unit: 1, q: 'Fungi are classified in their own kingdom because they:', choices: ['Are photosynthetic', 'Are prokaryotic', 'Are heterotrophs with cell walls made of chitin', 'Lack a cell wall'], answer: 2 },
      { unit: 1, q: 'A population is defined as:', choices: ['All organisms in an ecosystem', 'All organisms of the same species in the same area', 'All producers in a community', 'A group of different species sharing resources'], answer: 1 },
      { unit: 1, q: 'Which is the correct description of emergent properties?', choices: ['Properties that exist at all levels equally', 'Novel properties that arise at higher levels of organization', 'Properties that appear only at the atomic level', 'Properties that disappear at higher levels'], answer: 1 },
      { unit: 1, q: 'Inductive reasoning involves:', choices: ['Starting with a general principle and making specific predictions', 'Drawing broad conclusions from specific observations', 'Testing a hypothesis under controlled conditions', 'Applying mathematical models to biological data'], answer: 1 },
      { unit: 1, q: 'Which microscope uses a beam of electrons rather than light?', choices: ['Light microscope', 'Confocal microscope', 'Electron microscope', 'Fluorescence microscope'], answer: 2 },
      { unit: 1, q: 'The term "species" refers to a group of organisms that:', choices: ['Share the same habitat', 'Can interbreed and produce fertile offspring', 'Have the same phenotype', 'Belong to the same genus'], answer: 1 },
      { unit: 1, q: 'Which of the following best describes a community?', choices: ['Populations of different species living together in an area', 'All organisms and their abiotic environment', 'A single group of interbreeding organisms', 'All ecosystems on Earth'], answer: 0 },
      { unit: 1, q: 'The dependent variable in an experiment is the one that:', choices: ['Is deliberately manipulated by the researcher', 'Remains constant throughout the experiment', 'Is measured in response to changes', 'Is chosen randomly'], answer: 2 },

      // ── UNIT 2 — Chemistry of Life ─────────────────────────────────────────
      { unit: 2, q: 'What type of bond is formed when two atoms share electrons?', choices: ['Ionic bond', 'Covalent bond', 'Hydrogen bond', 'Van der Waals interaction'], answer: 1 },
      { unit: 2, q: 'Water molecules are attracted to each other through:', choices: ['Covalent bonds', 'Ionic bonds', 'Hydrogen bonds', 'Peptide bonds'], answer: 2 },
      { unit: 2, q: 'Which pH value represents a neutral solution?', choices: ['0', '7', '14', '4'], answer: 1 },
      { unit: 2, q: 'A solution with pH 3 is:', choices: ['Basic', 'Neutral', 'Acidic', 'Alkaline'], answer: 2 },
      { unit: 2, q: 'The monomer of proteins is:', choices: ['Nucleotide', 'Monosaccharide', 'Fatty acid', 'Amino acid'], answer: 3 },
      { unit: 2, q: 'Which macromolecule stores genetic information?', choices: ['Carbohydrates', 'Lipids', 'Proteins', 'Nucleic acids'], answer: 3 },
      { unit: 2, q: 'Glucose is an example of a:', choices: ['Disaccharide', 'Monosaccharide', 'Polysaccharide', 'Nucleotide'], answer: 1 },
      { unit: 2, q: 'Which of the following is a function of lipids?', choices: ['Catalyzing reactions', 'Storing energy and forming cell membranes', 'Carrying genetic information', 'Building cell walls of bacteria'], answer: 1 },
      { unit: 2, q: 'Enzymes speed up chemical reactions by:', choices: ['Raising the temperature', 'Providing energy', 'Lowering activation energy', 'Increasing substrate concentration'], answer: 2 },
      { unit: 2, q: 'The specific shape of an enzyme that binds its substrate is called the:', choices: ['Active site', 'Binding region', 'Catalytic domain', 'Substrate pocket'], answer: 0 },
      { unit: 2, q: 'A dehydration synthesis reaction:', choices: ['Adds water to break polymers', 'Removes water to join monomers', 'Uses ATP to form bonds', 'Breaks covalent bonds using enzymes'], answer: 1 },
      { unit: 2, q: 'Cellulose is a structural polysaccharide found in:', choices: ['Animal muscle', 'Plant cell walls', 'Bacterial cell walls', 'Fungal cell walls'], answer: 1 },
      { unit: 2, q: 'Which property of water allows it to resist rapid temperature changes?', choices: ['Cohesion', 'High specific heat', 'Polarity', 'Low surface tension'], answer: 1 },
      { unit: 2, q: 'Phospholipids have a _____ head and _____ tails.', choices: ['Nonpolar; polar', 'Polar; nonpolar', 'Charged; uncharged', 'Saturated; unsaturated'], answer: 1 },
      { unit: 2, q: 'Which of the following is true about saturated fatty acids?', choices: ['They have one or more double bonds', 'They are liquid at room temperature', 'They have no double bonds in their carbon chains', 'They are found mainly in plants'], answer: 2 },
      { unit: 2, q: 'DNA and RNA are polymers made of:', choices: ['Amino acids', 'Fatty acids', 'Nucleotides', 'Monosaccharides'], answer: 2 },
      { unit: 2, q: 'When an enzyme is denatured, it:', choices: ['Becomes more active', 'Loses its three-dimensional shape and function', 'Produces more products', 'Lowers its activation energy further'], answer: 1 },
      { unit: 2, q: 'Glycogen is the storage form of glucose in:', choices: ['Plants', 'Bacteria', 'Animals', 'Fungi'], answer: 2 },
      { unit: 2, q: 'A base on the pH scale:', choices: ['Donates H⁺ ions', 'Has a pH below 7', 'Accepts H⁺ ions', 'Increases the concentration of H⁺'], answer: 2 },
      { unit: 2, q: 'Which of the following is a carbohydrate?', choices: ['Cholesterol', 'Testosterone', 'Starch', 'Hemoglobin'], answer: 2 },
      { unit: 2, q: 'An acid solution has a higher concentration of:', choices: ['OH⁻ ions', 'H⁺ ions', 'Na⁺ ions', 'Cl⁻ ions'], answer: 1 },
      { unit: 2, q: 'The four levels of protein structure are:', choices: ['Primary, secondary, tertiary, quaternary', 'Alpha, beta, gamma, delta', 'Monomer, dimer, trimer, tetramer', 'Ionic, covalent, hydrogen, van der Waals'], answer: 0 },
      { unit: 2, q: 'Hydrolysis is the reaction that:', choices: ['Joins monomers using water', 'Breaks polymers by adding water', 'Removes water to form covalent bonds', 'Uses ATP to break bonds'], answer: 1 },
      { unit: 2, q: 'Which element is found in proteins but NOT in carbohydrates or lipids?', choices: ['Carbon', 'Hydrogen', 'Nitrogen', 'Oxygen'], answer: 2 },
      { unit: 2, q: 'Cohesion in water refers to:', choices: ['Water sticking to other substances', 'Water molecules sticking to each other', 'Water resisting temperature change', 'Water dissolving polar solutes'], answer: 1 },
      { unit: 2, q: 'Which macromolecule is the primary structural component of cell membranes?', choices: ['Proteins', 'Carbohydrates', 'Phospholipids', 'Nucleic acids'], answer: 2 },
      { unit: 2, q: 'Starch is a polysaccharide used for energy storage in:', choices: ['Animals', 'Fungi', 'Plants', 'Bacteria'], answer: 2 },
      { unit: 2, q: 'A buffer solution:', choices: ['Changes pH dramatically when acid is added', 'Resists changes in pH', 'Is always at pH 7', 'Contains no H⁺ ions'], answer: 1 },
      { unit: 2, q: 'Peptide bonds form between:', choices: ['Nucleotides', 'Monosaccharides', 'Amino acids', 'Fatty acids'], answer: 2 },
      { unit: 2, q: 'The unique properties of water (cohesion, high specific heat, etc.) arise primarily from:', choices: ['Its large molecular size', 'Its hydrogen bonds', 'Its ionic character', 'Its nonpolar nature'], answer: 1 },
      { unit: 2, q: 'Which of the following is a disaccharide?', choices: ['Glucose', 'Starch', 'Sucrose', 'Glycogen'], answer: 2 },

      // ── UNIT 3 — Cell Biology ──────────────────────────────────────────────
      { unit: 3, q: 'Which organelle is known as the "powerhouse of the cell"?', choices: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'], answer: 2 },
      { unit: 3, q: 'Which organelle synthesizes proteins?', choices: ['Lysosome', 'Ribosome', 'Vacuole', 'Centrosome'], answer: 1 },
      { unit: 3, q: 'Prokaryotic cells differ from eukaryotic cells in that they:', choices: ['Have a larger size', 'Lack membrane-bound organelles', 'Have a nucleus', 'Contain mitochondria'], answer: 1 },
      { unit: 3, q: 'Which of the following is found in plant cells but NOT in animal cells?', choices: ['Mitochondria', 'Ribosome', 'Chloroplast', 'Cell membrane'], answer: 2 },
      { unit: 3, q: 'The overall equation for photosynthesis is:', choices: ['C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP', '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂', '6CO₂ + 6O₂ → C₆H₁₂O₆ + H₂O', 'C₆H₁₂O₆ → 2 C₃H₄O₃ + 2ATP'], answer: 1 },
      { unit: 3, q: 'Cellular respiration primarily occurs in which organelle?', choices: ['Chloroplast', 'Nucleus', 'Ribosome', 'Mitochondria'], answer: 3 },
      { unit: 3, q: 'Which stage of cellular respiration occurs in the cytoplasm?', choices: ['Krebs cycle', 'Electron transport chain', 'Glycolysis', 'Pyruvate oxidation'], answer: 2 },
      { unit: 3, q: 'The net ATP yield from glycolysis is:', choices: ['4 ATP', '2 ATP', '36 ATP', '38 ATP'], answer: 1 },
      { unit: 3, q: 'What is the role of the Golgi apparatus?', choices: ['DNA replication', 'Protein synthesis', 'Processing and packaging proteins for secretion', 'Producing ATP'], answer: 2 },
      { unit: 3, q: 'The cell membrane is described as "fluid mosaic" because:', choices: ['It is a rigid structure', 'Phospholipids and proteins can move laterally', 'It is made entirely of carbohydrates', 'It only allows water to pass through'], answer: 1 },
      { unit: 3, q: 'Osmosis is the diffusion of _____ across a selectively permeable membrane.', choices: ['Glucose', 'Ions', 'Water', 'Proteins'], answer: 2 },
      { unit: 3, q: 'A cell placed in a hypotonic solution will:', choices: ['Shrink', 'Stay the same', 'Swell and potentially burst', 'Undergo apoptosis'], answer: 2 },
      { unit: 3, q: 'Active transport requires:', choices: ['A concentration gradient', 'ATP energy', 'A hypotonic solution', 'Aquaporins'], answer: 1 },
      { unit: 3, q: 'The light-dependent reactions of photosynthesis take place in the:', choices: ['Stroma', 'Thylakoid membrane', 'Cytoplasm', 'Outer chloroplast membrane'], answer: 1 },
      { unit: 3, q: 'The Calvin cycle fixes CO₂ into organic molecules using:', choices: ['Sunlight directly', 'ATP and NADPH from the light reactions', 'Glucose from glycolysis', 'O₂ from the atmosphere'], answer: 1 },
      { unit: 3, q: 'Which process produces oxygen as a byproduct?', choices: ['Cellular respiration', 'Glycolysis', 'Fermentation', 'Photosynthesis'], answer: 3 },
      { unit: 3, q: 'Lactic acid fermentation occurs in:', choices: ['Plant chloroplasts', 'Yeast cells', 'Animal muscle cells during intense exercise', 'Mitochondria'], answer: 2 },
      { unit: 3, q: 'Which organelle contains hydrolytic enzymes for digestion within the cell?', choices: ['Ribosome', 'Lysosome', 'Peroxisome', 'Golgi apparatus'], answer: 1 },
      { unit: 3, q: 'The smooth endoplasmic reticulum is primarily involved in:', choices: ['Protein synthesis', 'Lipid synthesis and detoxification', 'DNA replication', 'RNA transcription'], answer: 1 },
      { unit: 3, q: 'Facilitated diffusion differs from simple diffusion because it:', choices: ['Requires ATP', 'Uses protein channels or carriers', 'Moves solutes against the concentration gradient', 'Requires a membrane-bound pump'], answer: 1 },
      { unit: 3, q: 'The electron transport chain is located in the:', choices: ['Outer mitochondrial membrane', 'Inner mitochondrial membrane', 'Mitochondrial matrix', 'Cytoplasm'], answer: 1 },
      { unit: 3, q: 'What is chemiosmosis?', choices: ['The movement of electrons through the ETC', 'The synthesis of glucose in the Calvin cycle', 'ATP production driven by the flow of H⁺ through ATP synthase', 'The conversion of pyruvate to acetyl-CoA'], answer: 2 },
      { unit: 3, q: 'How many ATP molecules are produced per glucose molecule in aerobic respiration?', choices: ['2', '4', 'About 36–38', 'About 100'], answer: 2 },
      { unit: 3, q: 'Chlorophyll primarily absorbs which colors of light?', choices: ['Green and yellow', 'Red and blue', 'Orange and violet', 'All colors equally'], answer: 1 },
      { unit: 3, q: 'The nucleus contains:', choices: ['Ribosomes and lipids', 'DNA and the nucleolus', 'ATP and enzymes for respiration', 'Chlorophyll and thylakoids'], answer: 1 },
      { unit: 3, q: 'In a hypertonic solution, a cell will:', choices: ['Gain water and swell', 'Lose water and shrink', 'Remain the same size', 'Undergo mitosis'], answer: 1 },
      { unit: 3, q: 'Which molecule is the direct product of the Calvin cycle?', choices: ['Glucose', 'ATP', 'G3P (glyceraldehyde-3-phosphate)', 'NADPH'], answer: 2 },
      { unit: 3, q: 'Rubisco catalyzes which step of the Calvin cycle?', choices: ['Reduction of 3-PGA', 'Regeneration of RuBP', 'Carbon fixation (CO₂ + RuBP)', 'Production of ATP'], answer: 2 },
      { unit: 3, q: 'The inner membrane of the mitochondria is highly folded into structures called:', choices: ['Thylakoids', 'Cristae', 'Stroma', 'Lamellae'], answer: 1 },
      { unit: 3, q: 'In which stage of cellular respiration is CO₂ directly released?', choices: ['Glycolysis', 'Electron transport chain', 'Krebs cycle', 'Both B and C'], answer: 2 },
      { unit: 3, q: 'Which of the following transports electrons in cellular respiration?', choices: ['ATP and ADP', 'NADH and FADH₂', 'Glucose and fructose', 'CO₂ and H₂O'], answer: 1 },
    ],
    get quiz() {
      return this.qbank.slice();
    }
  }
];
