/* global CLASSES */
'use strict';

const CLASSES = [
  {
    id: 'biology-honors',
    name: 'Biology Honors',
    description: 'Advanced study of life science covering molecular biology, cell structure, genetics, evolution, and ecology.',
    unit: 'Science',
    icon: '🧬',
    studyGuides: [
      {
        title: 'Unit 1 — Introduction to Biology',
        content: [
          'Biology is the scientific study of life and living organisms.',
          'The eight properties of life: order, metabolism, growth/development, response to stimuli, reproduction, homeostasis, evolutionary adaptation, and cells.',
          'The three domains of life are Bacteria, Archaea, and Eukarya; kingdoms include Animalia, Plantae, Fungi, Protista.',
          'The biological hierarchy from smallest to largest: atom → molecule → organelle → cell → tissue → organ → organ system → organism → population → community → ecosystem → biosphere.',
          'The scientific method: observation → question → hypothesis → experiment → data analysis → conclusion.',
          'A controlled experiment has an independent variable, a dependent variable, and a control group.',
          'Evolution is the change in heritable traits of a population over successive generations.',
          'Natural selection: organisms with favorable traits are more likely to survive and reproduce.',
          'Taxonomy classifies organisms using: Domain, Kingdom, Phylum, Class, Order, Family, Genus, Species.',
          'Binomial nomenclature uses genus and species names (e.g., Homo sapiens) in italics.',
        ]
      },
      {
        title: 'Unit 2 — Chemistry of Life',
        content: [
          'All matter is made of atoms; atoms bond to form molecules.',
          'Covalent bonds share electrons; ionic bonds transfer electrons between atoms.',
          'Hydrogen bonds are weak attractions between slightly positive H and slightly negative atoms (O or N).',
          'Water is polar, enabling hydrogen bonds and cohesion, adhesion, and high specific heat.',
          'The pH scale ranges from 0 (most acidic) to 14 (most basic/alkaline); pH 7 is neutral.',
          'Acids donate H⁺ ions; bases accept H⁺ ions (or donate OH⁻).',
          'Biological macromolecules: carbohydrates, lipids, proteins, and nucleic acids.',
          'Carbohydrates (sugars): monomer = monosaccharide; polymer = polysaccharide; functions include energy storage (glycogen, starch) and structure (cellulose).',
          'Lipids: fats, oils, phospholipids, waxes; not polymers; functions include energy storage, membrane structure, and insulation.',
          'Proteins: monomer = amino acid; polymer = polypeptide; functions include enzymes, transport, structure, signaling, and defense.',
          'Nucleic acids: monomer = nucleotide; polymers = DNA and RNA; store and transfer genetic information.',
          'Enzymes are biological catalysts that lower activation energy; they are specific to their substrate.',
        ]
      },
      {
        title: 'Unit 3 — Cell Biology',
        content: [
          'Cell theory: all living things are made of cells; the cell is the basic unit of life; all cells come from pre-existing cells.',
          'Prokaryotic cells (Bacteria, Archaea): no membrane-bound nucleus, no membrane-bound organelles, smaller (~1–10 µm).',
          'Eukaryotic cells (animals, plants, fungi, protists): membrane-bound nucleus, membrane-bound organelles, larger (~10–100 µm).',
          'Key organelles: nucleus (DNA storage), mitochondria (ATP production), ribosomes (protein synthesis), ER (processing), Golgi apparatus (packaging/shipping).',
          'Plant cells also have: cell wall, chloroplasts, central vacuole, plasmodesmata.',
          'Photosynthesis occurs in chloroplasts: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂.',
          'Light reactions (thylakoid membrane) convert light to ATP and NADPH; Calvin cycle (stroma) fixes CO₂ into G3P.',
          'Cellular respiration occurs mainly in mitochondria: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ~36–38 ATP.',
          'Glycolysis (cytoplasm) → Pyruvate oxidation → Krebs cycle (matrix) → Electron transport chain (inner membrane).',
          'Fermentation (anaerobic): lactic acid fermentation or alcoholic fermentation; produces only 2 ATP net.',
          'The plasma membrane is a phospholipid bilayer with embedded proteins; it is selectively permeable.',
          'Passive transport: diffusion, osmosis, facilitated diffusion (no energy); active transport uses ATP.',
          'Chlorophyll a and b absorb red and blue light most efficiently; green light is reflected (why plants look green).',
          'The light-dependent reactions split water (photolysis) to produce O₂, ATP, and NADPH.',
          'Photosystem II absorbs light at ~680 nm; Photosystem I absorbs at ~700 nm.',
          'The Calvin cycle requires 3 CO₂, 9 ATP, and 6 NADPH to produce one G3P molecule.',
          'Rubisco is the enzyme that catalyzes carbon fixation in the Calvin cycle.',
          'Aerobic respiration produces ~36–38 ATP per glucose; most ATP is made at the ETC.',
          'The electron transport chain uses NADH and FADH₂ to pump H⁺ across the inner mitochondrial membrane, driving ATP synthase.',
          'Chemiosmosis: flow of H⁺ through ATP synthase drives phosphorylation of ADP → ATP.',
          'Substrate-level phosphorylation produces ATP directly during glycolysis and the Krebs cycle.',
          'Acetyl-CoA enters the Krebs cycle and is fully oxidized, releasing CO₂ and producing NADH, FADH₂, and ATP.',
        ]
      },
      {
        title: 'Unit 4 — Cell Reproduction & Genetics',
        content: [
          // ── Cell Reproduction ──────────────────────────────────────────────
          'Asexual reproduction produces offspring that are genetically identical to the parent (e.g., binary fission in bacteria, budding in yeast). Sexual reproduction combines genetic material from two parents, producing genetically unique offspring (e.g., human fertilization).',
          'Sexual reproduction drives genetic variability; the reshuffling of alleles during meiosis and fertilization generates new combinations not found in either parent.',
          'Mitosis purpose: growth, tissue repair, and asexual reproduction — produces two genetically identical diploid daughter cells. Meiosis purpose: sexual reproduction — produces four genetically unique haploid gametes.',
          'Chromosome anatomy: a chromosome consists of a highly coiled DNA molecule wrapped around histone proteins (forming chromatin). After replication, each chromosome consists of two identical sister chromatids joined at the centromere.',
          'A chromosome is the entire condensed structure; a chromatid is one of the two identical copies that make up a replicated chromosome. Sister chromatids are joined at the centromere and separate during cell division.',
          'Humans have 46 chromosomes arranged as 23 homologous pairs: 22 pairs of autosomes and 1 pair of sex chromosomes (XX in females, XY in males).',
          'Diploid (2n) cells contain two complete sets of chromosomes (one from each parent); haploid (n) cells contain one set. Human diploid = 46 chromosomes; human haploid = 23 chromosomes.',
          'Cell cycle phases: Interphase (G₁ — cell growth; S — DNA replication; G₂ — preparation for division) → M phase (mitosis + cytokinesis). G₀ is a non-dividing resting state.',
          'Phases of mitosis — Prophase: chromatin condenses, spindle forms, nuclear envelope breaks down. Metaphase: chromosomes align at the metaphase plate. Anaphase: sister chromatids pulled to opposite poles. Telophase: nuclear envelopes reform, chromosomes decondense.',
          'Cytokinesis in animal cells: a cleavage furrow (ring of microfilaments) pinches the cell in two. In plant cells: vesicles fuse at the center to form a cell plate, which grows into a new cell wall.',
          'Cancer is the uncontrolled division of cells caused by mutations in genes that regulate the cell cycle — specifically, activation of proto-oncogenes (which become oncogenes) and inactivation of tumor suppressor genes.',
          'Homologous chromosomes (homologs) are pairs of chromosomes that carry genes for the same traits at the same loci; one is inherited from each parent. They are similar in size, shape, and gene content but are not identical.',
          'Relationship: a chromosome is made of DNA and proteins; a gene is a specific segment of DNA on a chromosome that codes for a trait; a locus is the specific location of a gene on a chromosome; an allele is a variant form of a gene at a given locus; a chromatid is one copy of a replicated chromosome.',
          'Haploid cells in humans are the gametes: sperm cells (produced by males) and egg cells / oocytes (produced by females), each containing 23 chromosomes.',
          'Meiosis I (reduction division): Prophase I — homologs pair up (synapsis), crossing over occurs; Metaphase I — homologous pairs align at the equator; Anaphase I — homologs pulled apart; Telophase I — two haploid cells form. Meiosis II (like mitosis): Prophase II → Metaphase II → Anaphase II (sister chromatids separate) → Telophase II — four haploid cells result.',
          'Key differences — Mitosis vs. Meiosis: mitosis has one division; meiosis has two. Mitosis produces 2 diploid identical cells; meiosis produces 4 haploid unique cells. Crossing over and synapsis occur only in meiosis. Meiosis reduces chromosome number by half.',
          'Crossing over (recombination): during Prophase I of meiosis, non-sister chromatids of homologous chromosomes exchange segments at points called chiasmata. This shuffles alleles between homologs and is a major source of genetic variation.',
          'Allele notation: dominant alleles are written as uppercase letters (e.g., A); recessive alleles are written as lowercase letters (e.g., a). Genotypes are written as letter pairs (e.g., AA, Aa, aa).',
          'Trisomy 21 is commonly called Down syndrome. It occurs when an individual has three copies of chromosome 21 (due to nondisjunction during meiosis), resulting in 47 total chromosomes.',
          // ── Genetics / Heredity ────────────────────────────────────────────
          'Gregor Mendel (1822–1884) was an Austrian monk who conducted systematic breeding experiments with pea plants, establishing the mathematical laws of inheritance. His work is the foundation of modern genetics.',
          'Genetics is the scientific study of heredity (the passing of traits from parents to offspring) and genetic variation. Heredity is the biological process by which traits are transmitted; genetics is the discipline that explains how and why.',
          'A character is a heritable feature (e.g., flower color); a trait is a specific variant of that character (e.g., purple flowers). Multiple traits exist for each character.',
          'Mendel studied the garden pea plant (Pisum sativum) and tracked seven characters: seed shape, seed color, pod shape, pod color, flower color, flower position, and plant height — each with two distinct traits.',
          'Self-pollination: a plant fertilizes itself using its own pollen — allows true-breeding lines. Cross-pollination: pollen from one plant fertilizes another — used to combine traits. Mendel controlled both to test specific trait combinations.',
          'Mendel\'s experiment: he first established true-breeding parental lines (P generation) for each trait. He then cross-pollinated plants with contrasting traits. The F₁ generation all showed one (dominant) trait. When F₁ plants self-pollinated, the F₂ generation showed both traits in approximately a 3:1 ratio.',
          'Generations: P (parental) — original true-breeding parents. F₁ (first filial) — first generation offspring from a P cross; all look like the dominant parent. F₂ (second filial) — offspring from an F₁ × F₁ cross; shows ~3:1 phenotype ratio.',
          'Dominant alleles are written as uppercase letters (e.g., B for brown eyes); recessive alleles are written as lowercase letters (e.g., b for blue eyes). A dominant allele masks the expression of a recessive allele in a heterozygote.',
          'An allele is one of two or more alternative versions of a gene that can occupy a given locus on a chromosome. Organisms inherit two alleles for each gene, one from each parent.',
          'Homozygous: both alleles at a locus are identical — either homozygous dominant (AA) or homozygous recessive (aa). Heterozygous: the two alleles at a locus are different (Aa). Example: AA = homozygous dominant tall; aa = homozygous recessive short; Aa = heterozygous (phenotypically tall).',
          'A phenotypic ratio describes the proportion of offspring showing each observable phenotype. Example: a monohybrid Aa × Aa cross gives a 3:1 phenotypic ratio — 3 dominant phenotype : 1 recessive phenotype.',
          'A genotypic ratio describes the proportion of offspring with each genotype. Example: Aa × Aa gives a 1:2:1 genotypic ratio — 1 AA : 2 Aa : 1 aa.',
          'Genotype is the genetic makeup of an organism (the alleles it carries, e.g., Aa). Phenotype is the observable physical or biochemical characteristic expressed (e.g., tall plant). Same phenotype can arise from different genotypes (AA and Aa are both phenotypically dominant).',
          'Mendel\'s four conclusions: (1) Traits are determined by discrete heritable units (genes). (2) Each organism inherits two copies of each gene, one from each parent. (3) When two different alleles are present, one (dominant) may mask the other (recessive). (4) The two alleles for each gene separate during gamete formation so each gamete carries only one allele (Law of Segregation).',
          'Hierarchy: chromosome → gene → allele → locus. A chromosome carries many genes; each gene occupies a specific locus on the chromosome; alleles are the different versions of a gene at that locus.',
          'Monohybrid cross — Aa × Aa (heterozygotes): use a Punnett square; outcomes are AA (25%), Aa (50%), aa (25%); phenotype ratio 3:1. Aa × AA (heterozygote × homozygous dominant): all phenotypically dominant; genotypes 50% AA, 50% Aa. Aa × aa (heterozygote × homozygous recessive): 50% Aa (dominant phenotype), 50% aa (recessive phenotype); phenotype ratio 1:1.',
          'A dihybrid cross studies the simultaneous inheritance of two independent characters (e.g., seed color AND seed shape). When two double heterozygotes (AaBb × AaBb) are crossed, the expected F₂ phenotype ratio is 9:3:3:1, demonstrating independent assortment.',
          'A pedigree is a diagram that traces the inheritance of a trait through multiple generations of a family. Symbols: squares represent males; circles represent females; filled shapes indicate affected individuals; half-filled shapes represent carriers; horizontal lines between a male and female indicate mating; vertical lines lead to offspring; a horizontal line connecting siblings is called a sibship line.',
        ]
      }
    ],
    qbank: [
      // ── UNIT 1 — Introduction to Biology ──────────────────────────────────
      { unit: 1, q: 'Which of the following is NOT considered a property of life?', choices: ['Reproduction', 'Metabolism', 'Crystalline structure', 'Homeostasis'], answer: 2 },
      { unit: 1, q: 'Which domain includes organisms with membrane-bound nuclei?', choices: ['Bacteria', 'Archaea', 'Eukarya', 'Protista'], answer: 2 },
      { unit: 1, q: 'The correct order of the biological hierarchy from smallest to largest is:', choices: ['Cell → Organ → Tissue → Organism', 'Atom → Molecule → Organelle → Cell', 'Ecosystem → Community → Population → Organism', 'Organ → Tissue → Cell → Organelle'], answer: 1 },
      { unit: 1, q: 'In a controlled experiment, the variable that the scientist deliberately changes is called the:', choices: ['Dependent variable', 'Controlled variable', 'Independent variable', 'Constant'], answer: 2 },
      { unit: 1, q: 'Which scientist proposed the theory of natural selection?', choices: ['Gregor Mendel', 'Louis Pasteur', 'Charles Darwin', 'Robert Hooke'], answer: 2 },
      { unit: 1, q: 'The scientific name Homo sapiens follows the system of:', choices: ['Binomial nomenclature', 'Systemic classification', 'Hierarchical taxonomy', 'Phenotypic grouping'], answer: 0 },
      { unit: 1, q: 'Natural selection acts on which of the following?', choices: ['Genotype only', 'Phenotype', 'DNA directly', 'Non-heritable traits'], answer: 1 },
      { unit: 1, q: 'Which level of biological organization is directly above the community?', choices: ['Population', 'Organism', 'Ecosystem', 'Biosphere'], answer: 2 },
      { unit: 1, q: 'A hypothesis must be:', choices: ['Proven true', 'Testable and falsifiable', 'Based on prior experiments only', 'Supported by multiple theories'], answer: 1 },
      { unit: 1, q: 'Taxonomy classifies organisms using which sequence?', choices: ['Kingdom, Phylum, Class, Order, Family, Genus, Species', 'Domain, Class, Kingdom, Order, Phylum, Genus, Species', 'Species, Genus, Family, Order, Class, Phylum, Kingdom', 'Domain, Phylum, Kingdom, Class, Family, Order, Species'], answer: 0 },
      { unit: 1, q: 'Archaea are most closely related to:', choices: ['Bacteria', 'Fungi', 'Plants', 'Eukarya'], answer: 3 },
      { unit: 1, q: 'The maintenance of a stable internal environment is called:', choices: ['Metabolism', 'Homeostasis', 'Adaptation', 'Reproduction'], answer: 1 },
      { unit: 1, q: 'Which of the following best defines evolution?', choices: ['Change in an individual organism over time', 'Change in heritable traits of a population over generations', 'Survival of the strongest individual', 'Genetic mutation in a single organism'], answer: 1 },
      { unit: 1, q: 'The control group in an experiment:', choices: ['Receives the experimental treatment', 'Is exposed to the independent variable', 'Is used as a baseline for comparison', 'Contains no constants'], answer: 2 },
      { unit: 1, q: 'Which kingdom contains multicellular organisms that perform photosynthesis?', choices: ['Fungi', 'Animalia', 'Plantae', 'Bacteria'], answer: 2 },
      { unit: 1, q: 'Which of the following is the broadest taxonomic category?', choices: ['Species', 'Genus', 'Kingdom', 'Domain'], answer: 3 },
      { unit: 1, q: 'Organisms that break down dead organic matter are called:', choices: ['Producers', 'Consumers', 'Decomposers', 'Herbivores'], answer: 2 },
      { unit: 1, q: 'The idea that all cells come from pre-existing cells is part of:', choices: ['Evolution theory', 'Cell theory', 'Germ theory', 'Gene theory'], answer: 1 },
      { unit: 1, q: 'Which process converts light energy into chemical energy?', choices: ['Cellular respiration', 'Fermentation', 'Photosynthesis', 'Chemosynthesis'], answer: 2 },
      { unit: 1, q: 'The process by which populations change over time in response to environmental pressures is called:', choices: ['Genetics', 'Evolution', 'Ecology', 'Taxonomy'], answer: 1 },
      { unit: 1, q: 'Which of the following is an example of an abiotic factor in an ecosystem?', choices: ['Trees', 'Bacteria', 'Temperature', 'Birds'], answer: 2 },
      { unit: 1, q: 'The scientific method begins with which step?', choices: ['Forming a hypothesis', 'Making an observation', 'Designing an experiment', 'Analyzing data'], answer: 1 },
      { unit: 1, q: 'Fungi are classified in their own kingdom because they:', choices: ['Are photosynthetic', 'Are prokaryotic', 'Are heterotrophs with cell walls made of chitin', 'Lack a cell wall'], answer: 2 },
      { unit: 1, q: 'A population is defined as:', choices: ['All organisms in an ecosystem', 'All organisms of the same species in the same area', 'All producers in a community', 'A group of different species sharing resources'], answer: 1 },
      { unit: 1, q: 'Which is the correct description of emergent properties?', choices: ['Properties that exist at all levels equally', 'Novel properties that arise at higher levels of organization', 'Properties that appear only at the atomic level', 'Properties that disappear at higher levels'], answer: 1 },
      { unit: 1, q: 'Inductive reasoning involves:', choices: ['Starting with a general principle and making specific predictions', 'Drawing broad conclusions from specific observations', 'Testing a hypothesis under controlled conditions', 'Applying mathematical models to biological data'], answer: 1 },
      { unit: 1, q: 'Which microscope uses a beam of electrons rather than light?', choices: ['Light microscope', 'Confocal microscope', 'Electron microscope', 'Fluorescence microscope'], answer: 2 },
      { unit: 1, q: 'The term "species" refers to a group of organisms that:', choices: ['Share the same habitat', 'Can interbreed and produce fertile offspring', 'Have the same phenotype', 'Belong to the same genus'], answer: 1 },
      { unit: 1, q: 'Which of the following best describes a community?', choices: ['Populations of different species living together in an area', 'All organisms and their abiotic environment', 'A single group of interbreeding organisms', 'All ecosystems on Earth'], answer: 0 },
      { unit: 1, q: 'The dependent variable in an experiment is the one that:', choices: ['Is deliberately manipulated by the researcher', 'Remains constant throughout the experiment', 'Is measured in response to changes', 'Is chosen randomly'], answer: 2 },

      // ── UNIT 2 — Chemistry of Life ─────────────────────────────────────────
      { unit: 2, q: 'What type of bond is formed when two atoms share electrons?', choices: ['Ionic bond', 'Covalent bond', 'Hydrogen bond', 'Van der Waals interaction'], answer: 1 },
      { unit: 2, q: 'Water molecules are attracted to each other through:', choices: ['Covalent bonds', 'Ionic bonds', 'Hydrogen bonds', 'Peptide bonds'], answer: 2 },
      { unit: 2, q: 'Which pH value represents a neutral solution?', choices: ['0', '7', '14', '4'], answer: 1 },
      { unit: 2, q: 'A solution with pH 3 is:', choices: ['Basic', 'Neutral', 'Acidic', 'Alkaline'], answer: 2 },
      { unit: 2, q: 'The monomer of proteins is:', choices: ['Nucleotide', 'Monosaccharide', 'Fatty acid', 'Amino acid'], answer: 3 },
      { unit: 2, q: 'Which macromolecule stores genetic information?', choices: ['Carbohydrates', 'Lipids', 'Proteins', 'Nucleic acids'], answer: 3 },
      { unit: 2, q: 'Glucose is an example of a:', choices: ['Disaccharide', 'Monosaccharide', 'Polysaccharide', 'Nucleotide'], answer: 1 },
      { unit: 2, q: 'Which of the following is a function of lipids?', choices: ['Catalyzing reactions', 'Storing energy and forming cell membranes', 'Carrying genetic information', 'Building cell walls of bacteria'], answer: 1 },
      { unit: 2, q: 'Enzymes speed up chemical reactions by:', choices: ['Raising the temperature', 'Providing energy', 'Lowering activation energy', 'Increasing substrate concentration'], answer: 2 },
      { unit: 2, q: 'The specific shape of an enzyme that binds its substrate is called the:', choices: ['Active site', 'Binding region', 'Catalytic domain', 'Substrate pocket'], answer: 0 },
      { unit: 2, q: 'A dehydration synthesis reaction:', choices: ['Adds water to break polymers', 'Removes water to join monomers', 'Uses ATP to form bonds', 'Breaks covalent bonds using enzymes'], answer: 1 },
      { unit: 2, q: 'Cellulose is a structural polysaccharide found in:', choices: ['Animal muscle', 'Plant cell walls', 'Bacterial cell walls', 'Fungal cell walls'], answer: 1 },
      { unit: 2, q: 'Which property of water allows it to resist rapid temperature changes?', choices: ['Cohesion', 'High specific heat', 'Polarity', 'Low surface tension'], answer: 1 },
      { unit: 2, q: 'Phospholipids have a _____ head and _____ tails.', choices: ['Nonpolar; polar', 'Polar; nonpolar', 'Charged; uncharged', 'Saturated; unsaturated'], answer: 1 },
      { unit: 2, q: 'Which of the following is true about saturated fatty acids?', choices: ['They have one or more double bonds', 'They are liquid at room temperature', 'They have no double bonds in their carbon chains', 'They are found mainly in plants'], answer: 2 },
      { unit: 2, q: 'DNA and RNA are polymers made of:', choices: ['Amino acids', 'Fatty acids', 'Nucleotides', 'Monosaccharides'], answer: 2 },
      { unit: 2, q: 'When an enzyme is denatured, it:', choices: ['Becomes more active', 'Loses its three-dimensional shape and function', 'Produces more products', 'Lowers its activation energy further'], answer: 1 },
      { unit: 2, q: 'Glycogen is the storage form of glucose in:', choices: ['Plants', 'Bacteria', 'Animals', 'Fungi'], answer: 2 },
      { unit: 2, q: 'A base on the pH scale:', choices: ['Donates H⁺ ions', 'Has a pH below 7', 'Accepts H⁺ ions', 'Increases the concentration of H⁺'], answer: 2 },
      { unit: 2, q: 'Which of the following is a carbohydrate?', choices: ['Cholesterol', 'Testosterone', 'Starch', 'Hemoglobin'], answer: 2 },
      { unit: 2, q: 'An acid solution has a higher concentration of:', choices: ['OH⁻ ions', 'H⁺ ions', 'Na⁺ ions', 'Cl⁻ ions'], answer: 1 },
      { unit: 2, q: 'The four levels of protein structure are:', choices: ['Primary, secondary, tertiary, quaternary', 'Alpha, beta, gamma, delta', 'Monomer, dimer, trimer, tetramer', 'Ionic, covalent, hydrogen, van der Waals'], answer: 0 },
      { unit: 2, q: 'Hydrolysis is the reaction that:', choices: ['Joins monomers using water', 'Breaks polymers by adding water', 'Removes water to form covalent bonds', 'Uses ATP to break bonds'], answer: 1 },
      { unit: 2, q: 'Which element is found in proteins but NOT in carbohydrates or lipids?', choices: ['Carbon', 'Hydrogen', 'Nitrogen', 'Oxygen'], answer: 2 },
      { unit: 2, q: 'Cohesion in water refers to:', choices: ['Water sticking to other substances', 'Water molecules sticking to each other', 'Water resisting temperature change', 'Water dissolving polar solutes'], answer: 1 },
      { unit: 2, q: 'Which macromolecule is the primary structural component of cell membranes?', choices: ['Proteins', 'Carbohydrates', 'Phospholipids', 'Nucleic acids'], answer: 2 },
      { unit: 2, q: 'Starch is a polysaccharide used for energy storage in:', choices: ['Animals', 'Fungi', 'Plants', 'Bacteria'], answer: 2 },
      { unit: 2, q: 'A buffer solution:', choices: ['Changes pH dramatically when acid is added', 'Resists changes in pH', 'Is always at pH 7', 'Contains no H⁺ ions'], answer: 1 },
      { unit: 2, q: 'Peptide bonds form between:', choices: ['Nucleotides', 'Monosaccharides', 'Amino acids', 'Fatty acids'], answer: 2 },
      { unit: 2, q: 'The unique properties of water (cohesion, high specific heat, etc.) arise primarily from:', choices: ['Its large molecular size', 'Its hydrogen bonds', 'Its ionic character', 'Its nonpolar nature'], answer: 1 },
      { unit: 2, q: 'Which of the following is a disaccharide?', choices: ['Glucose', 'Starch', 'Sucrose', 'Glycogen'], answer: 2 },

      // ── UNIT 3 — Cell Biology ──────────────────────────────────────────────
      { unit: 3, q: 'Which organelle is known as the "powerhouse of the cell"?', choices: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'], answer: 2 },
      { unit: 3, q: 'Which organelle synthesizes proteins?', choices: ['Lysosome', 'Ribosome', 'Vacuole', 'Centrosome'], answer: 1 },
      { unit: 3, q: 'Prokaryotic cells differ from eukaryotic cells in that they:', choices: ['Have a larger size', 'Lack membrane-bound organelles', 'Have a nucleus', 'Contain mitochondria'], answer: 1 },
      { unit: 3, q: 'Which of the following is found in plant cells but NOT in animal cells?', choices: ['Mitochondria', 'Ribosome', 'Chloroplast', 'Cell membrane'], answer: 2 },
      { unit: 3, q: 'The overall equation for photosynthesis is:', choices: ['C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP', '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂', '6CO₂ + 6O₂ → C₆H₁₂O₆ + H₂O', 'C₆H₁₂O₆ → 2 C₃H₄O₃ + 2ATP'], answer: 1 },
      { unit: 3, q: 'Cellular respiration primarily occurs in which organelle?', choices: ['Chloroplast', 'Nucleus', 'Ribosome', 'Mitochondria'], answer: 3 },
      { unit: 3, q: 'Which stage of cellular respiration occurs in the cytoplasm?', choices: ['Krebs cycle', 'Electron transport chain', 'Glycolysis', 'Pyruvate oxidation'], answer: 2 },
      { unit: 3, q: 'The net ATP yield from glycolysis is:', choices: ['4 ATP', '2 ATP', '36 ATP', '38 ATP'], answer: 1 },
      { unit: 3, q: 'What is the role of the Golgi apparatus?', choices: ['DNA replication', 'Protein synthesis', 'Processing and packaging proteins for secretion', 'Producing ATP'], answer: 2 },
      { unit: 3, q: 'The cell membrane is described as "fluid mosaic" because:', choices: ['It is a rigid structure', 'Phospholipids and proteins can move laterally', 'It is made entirely of carbohydrates', 'It only allows water to pass through'], answer: 1 },
      { unit: 3, q: 'Osmosis is the diffusion of _____ across a selectively permeable membrane.', choices: ['Glucose', 'Ions', 'Water', 'Proteins'], answer: 2 },
      { unit: 3, q: 'A cell placed in a hypotonic solution will:', choices: ['Shrink', 'Stay the same', 'Swell and potentially burst', 'Undergo apoptosis'], answer: 2 },
      { unit: 3, q: 'Active transport requires:', choices: ['A concentration gradient', 'ATP energy', 'A hypotonic solution', 'Aquaporins'], answer: 1 },
      { unit: 3, q: 'The light-dependent reactions of photosynthesis take place in the:', choices: ['Stroma', 'Thylakoid membrane', 'Cytoplasm', 'Outer chloroplast membrane'], answer: 1 },
      { unit: 3, q: 'The Calvin cycle fixes CO₂ into organic molecules using:', choices: ['Sunlight directly', 'ATP and NADPH from the light reactions', 'Glucose from glycolysis', 'O₂ from the atmosphere'], answer: 1 },
      { unit: 3, q: 'Which process produces oxygen as a byproduct?', choices: ['Cellular respiration', 'Glycolysis', 'Fermentation', 'Photosynthesis'], answer: 3 },
      { unit: 3, q: 'Lactic acid fermentation occurs in:', choices: ['Plant chloroplasts', 'Yeast cells', 'Animal muscle cells during intense exercise', 'Mitochondria'], answer: 2 },
      { unit: 3, q: 'Which organelle contains hydrolytic enzymes for digestion within the cell?', choices: ['Ribosome', 'Lysosome', 'Peroxisome', 'Golgi apparatus'], answer: 1 },
      { unit: 3, q: 'The smooth endoplasmic reticulum is primarily involved in:', choices: ['Protein synthesis', 'Lipid synthesis and detoxification', 'DNA replication', 'RNA transcription'], answer: 1 },
      { unit: 3, q: 'Facilitated diffusion differs from simple diffusion because it:', choices: ['Requires ATP', 'Uses protein channels or carriers', 'Moves solutes against the concentration gradient', 'Requires a membrane-bound pump'], answer: 1 },
      { unit: 3, q: 'The electron transport chain is located in the:', choices: ['Outer mitochondrial membrane', 'Inner mitochondrial membrane', 'Mitochondrial matrix', 'Cytoplasm'], answer: 1 },
      { unit: 3, q: 'What is chemiosmosis?', choices: ['The movement of electrons through the ETC', 'The synthesis of glucose in the Calvin cycle', 'ATP production driven by the flow of H⁺ through ATP synthase', 'The conversion of pyruvate to acetyl-CoA'], answer: 2 },
      { unit: 3, q: 'How many ATP molecules are produced per glucose molecule in aerobic respiration?', choices: ['2', '4', 'About 36–38', 'About 100'], answer: 2 },
      { unit: 3, q: 'Chlorophyll primarily absorbs which colors of light?', choices: ['Green and yellow', 'Red and blue', 'Orange and violet', 'All colors equally'], answer: 1 },
      { unit: 3, q: 'The nucleus contains:', choices: ['Ribosomes and lipids', 'DNA and the nucleolus', 'ATP and enzymes for respiration', 'Chlorophyll and thylakoids'], answer: 1 },
      { unit: 3, q: 'In a hypertonic solution, a cell will:', choices: ['Gain water and swell', 'Lose water and shrink', 'Remain the same size', 'Undergo mitosis'], answer: 1 },
      { unit: 3, q: 'Which molecule is the direct product of the Calvin cycle?', choices: ['Glucose', 'ATP', 'G3P (glyceraldehyde-3-phosphate)', 'NADPH'], answer: 2 },
      { unit: 3, q: 'Rubisco catalyzes which step of the Calvin cycle?', choices: ['Reduction of 3-PGA', 'Regeneration of RuBP', 'Carbon fixation (CO₂ + RuBP)', 'Production of ATP'], answer: 2 },
      { unit: 3, q: 'The inner membrane of the mitochondria is highly folded into structures called:', choices: ['Thylakoids', 'Cristae', 'Stroma', 'Lamellae'], answer: 1 },
      { unit: 3, q: 'In which stage of cellular respiration is CO₂ directly released?', choices: ['Glycolysis', 'Electron transport chain', 'Krebs cycle', 'Both B and C'], answer: 2 },
      { unit: 3, q: 'Which of the following transports electrons in cellular respiration?', choices: ['ATP and ADP', 'NADH and FADH₂', 'Glucose and fructose', 'CO₂ and H₂O'], answer: 1 },

      // ── UNIT 4 — Cell Reproduction & Genetics ─────────────────────────────
      { unit: 4, q: 'Which type of reproduction produces offspring that are genetically identical to the parent?', choices: ['Sexual reproduction', 'Asexual reproduction', 'Meiotic reproduction', 'Cross-pollination'], answer: 1 },
      { unit: 4, q: 'Which type of reproduction is the primary driver of genetic variability in a population?', choices: ['Asexual reproduction', 'Binary fission', 'Sexual reproduction', 'Budding'], answer: 2 },
      { unit: 4, q: 'The primary purpose of mitosis is:', choices: ['To produce haploid gametes for reproduction', 'To create genetic diversity through crossing over', 'To produce genetically identical diploid cells for growth and repair', 'To reduce the chromosome number by half'], answer: 2 },
      { unit: 4, q: 'A chromosome that has been replicated consists of two identical:', choices: ['Homologous chromosomes joined at the centromere', 'Sister chromatids joined at the centromere', 'Chromatids joined at the telomere', 'Genes joined by histone proteins'], answer: 1 },
      { unit: 4, q: 'What is the difference between a chromosome and a chromatid?', choices: ['A chromosome is haploid; a chromatid is diploid', 'A chromatid is the entire structure; a chromosome is one copy', 'A chromosome is the entire condensed structure; a chromatid is one of two identical copies of a replicated chromosome', 'They are the same thing at different stages'], answer: 2 },
      { unit: 4, q: 'How many chromosomes does a normal human somatic (body) cell have?', choices: ['23', '46', '44', '92'], answer: 1 },
      { unit: 4, q: 'A diploid cell contains:', choices: ['One complete set of chromosomes', 'Two complete sets of chromosomes (one from each parent)', 'Four sets of chromosomes', 'Only sex chromosomes'], answer: 1 },
      { unit: 4, q: 'During which phase of interphase does DNA replication occur?', choices: ['G₁ phase', 'G₂ phase', 'S phase', 'G₀ phase'], answer: 2 },
      { unit: 4, q: 'During which phase of mitosis do chromosomes align along the cell\'s equatorial plate?', choices: ['Prophase', 'Metaphase', 'Anaphase', 'Telophase'], answer: 1 },
      { unit: 4, q: 'How does cytokinesis differ between plant and animal cells?', choices: ['Animal cells form a cell plate; plant cells form a cleavage furrow', 'Plant cells form a cell plate; animal cells form a cleavage furrow', 'Both form cleavage furrows but at different speeds', 'Plant cells do not undergo cytokinesis'], answer: 1 },
      { unit: 4, q: 'Cancer is best described as:', choices: ['A viral infection that destroys cells', 'Programmed cell death occurring too rapidly', 'Uncontrolled cell division due to mutations in cell cycle regulatory genes', 'A type of normal differentiation that goes wrong'], answer: 2 },
      { unit: 4, q: 'Homologous chromosomes are best described as:', choices: ['Two identical copies of a replicated chromosome', 'Chromosomes that carry genes for the same traits at the same loci, one from each parent', 'Any two chromosomes in a haploid cell', 'Chromosomes that have undergone crossing over'], answer: 1 },
      { unit: 4, q: 'A locus is defined as:', choices: ['A variant form of a gene', 'The entire set of an organism\'s DNA', 'The specific location of a gene on a chromosome', 'A segment of DNA that codes for a protein'], answer: 2 },
      { unit: 4, q: 'Which of the following are the haploid cells found in humans?', choices: ['Red blood cells and white blood cells', 'Liver cells and muscle cells', 'Sperm cells and egg cells (gametes)', 'Stem cells and progenitor cells'], answer: 2 },
      { unit: 4, q: 'Crossing over occurs during which phase of meiosis?', choices: ['Metaphase II', 'Anaphase I', 'Prophase I', 'Telophase II'], answer: 2 },
      { unit: 4, q: 'What is the result of crossing over?', choices: ['Sister chromatids become joined at the centromere', 'Homologous chromosomes exchange segments, creating new allele combinations', 'Chromosomes are pulled to opposite poles', 'The chromosome number is reduced by half'], answer: 1 },
      { unit: 4, q: 'In genetics, a dominant allele is written as:', choices: ['A lowercase letter (e.g., a)', 'An uppercase letter (e.g., A)', 'A number (e.g., A1)', 'A Greek letter (e.g., α)'], answer: 1 },
      { unit: 4, q: 'Trisomy 21 is the chromosomal basis of:', choices: ['Turner syndrome', 'Klinefelter syndrome', 'Down syndrome', 'Cri-du-chat syndrome'], answer: 2 },
      { unit: 4, q: 'Who conducted the foundational breeding experiments that established the laws of inheritance?', choices: ['Charles Darwin', 'James Watson', 'Gregor Mendel', 'Thomas Morgan'], answer: 2 },
      { unit: 4, q: 'What is the relationship between genetics and heredity?', choices: ['They are completely unrelated fields', 'Heredity is the passing of traits to offspring; genetics is the scientific study of heredity and variation', 'Genetics studies only DNA structure; heredity studies only phenotypes', 'Heredity applies only to animals; genetics applies only to plants'], answer: 1 },
      { unit: 4, q: 'A "character" in genetics refers to:', choices: ['A specific variant of a heritable feature (e.g., purple flowers)', 'A heritable feature that can vary among individuals (e.g., flower color)', 'The genotype of an organism', 'The environment\'s influence on a phenotype'], answer: 1 },
      { unit: 4, q: 'Mendel studied which organism for his breeding experiments?', choices: ['Fruit flies (Drosophila melanogaster)', 'Garden pea plants (Pisum sativum)', 'Baker\'s yeast (Saccharomyces cerevisiae)', 'Common bread mold (Neurospora crassa)'], answer: 1 },
      { unit: 4, q: 'In Mendel\'s monohybrid cross experiments, the F₁ generation:', choices: ['Showed both parental traits equally', 'Showed a 3:1 ratio of dominant to recessive traits', 'All displayed the dominant trait only', 'All displayed the recessive trait only'], answer: 2 },
      { unit: 4, q: 'An organism that carries two different alleles for a trait (e.g., Aa) is called:', choices: ['Homozygous dominant', 'Homozygous recessive', 'Heterozygous', 'Codominant'], answer: 2 },
      { unit: 4, q: 'The phenotypic ratio produced by a monohybrid cross between two heterozygotes (Aa × Aa) is:', choices: ['1:2:1', '3:1', '1:1', '9:3:3:1'], answer: 1 },
      { unit: 4, q: 'Which of the following correctly defines genotype vs. phenotype?', choices: ['Genotype is the observable trait; phenotype is the genetic makeup', 'Genotype is the genetic makeup (alleles); phenotype is the observable trait expressed', 'They are interchangeable terms for the same concept', 'Genotype refers only to dominant alleles; phenotype refers to recessive alleles'], answer: 1 },
      { unit: 4, q: 'In a pedigree chart, a filled square represents:', choices: ['An unaffected female', 'An affected female', 'An unaffected male', 'An affected male'], answer: 3 },
      { unit: 4, q: 'Mendel\'s Law of Segregation states that:', choices: ['Traits from both parents blend together in offspring', 'The two alleles for a gene separate during gamete formation so each gamete carries only one allele', 'Genes on different chromosomes are always inherited together', 'Dominant alleles increase in frequency each generation'], answer: 1 },
      { unit: 4, q: 'A dihybrid cross differs from a monohybrid cross in that it:', choices: ['Uses haploid organisms', 'Studies the simultaneous inheritance of two different characters', 'Produces only recessive offspring', 'Requires self-pollination only'], answer: 1 },
      { unit: 4, q: 'Which of the following correctly ranks the chromosomal components from largest to smallest?', choices: ['Gene → Chromosome → Locus → Allele', 'Chromosome → Gene → Locus → Allele', 'Locus → Gene → Allele → Chromosome', 'Allele → Gene → Locus → Chromosome'], answer: 1 },
    ],
    get quiz() {
      return this.qbank.slice();
    }
  }
];
